name: My first workflow

on: push # Workflow will trigger after pushing the new commit in repo" 
jobs:
    my-first-job:
      runs-on: ubuntu-latest # "Github hosted runner"
      steps:
        - name: checkout repo
          uses: actions/checkout@v5

        - name: listing the files
          run: ls -ltarh

        - name: Read the content
          run: cat README.md